# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Install git for pip install via git
RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Install MCP SDK
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir "git+https://github.com/modelcontextprotocol/python-sdk.git@main#egg=mcp[fastapi]"

# Copy application source
COPY . .

# Default command
CMD ["python", "advanced_calculator_server.py"]
